### ISSUE TITLE
Any progress on fixing the drivers?

### ISSUE THREAD

**Issue by sapertuz** [Kampi/OV7670#1]
Hi Daniel,

I am Dozent in germany too and I would like to use this IP for a lecture lab rather soon.
It's a lecture about fpga for robotics and this OV7670 cheap sensor is perfect for an activity :)

I was wondering whether you had made any progress on the drivers of this IP to make it usable.
If not, I would like to contribute by doing part of the rework myself, but would appreciate any instructions on what should be done.

Looking forward to your reply :)

Best,
Sergio

**Comment by Kampi** [comment]
Hi Sergio.

it looks like an old one and I´m not sure about the state.

You can check [this](https://github.com/Kampi/ZYBO/tree/master/projects/DigitalVideo) for a working version. There you find the directory `ip_repo` with a complete IP core and a software driver and also a `BasicVideo` project in the `projects` directory. This project is running on a ZYBO with my [OV7670 board](https://github.com/Kampi/ZYBO/tree/master/pmod/OV7670).

**Comment by sapertuz** [comment]
Ah ok... because the las commit said 10 months ago, I assumed this was more recent.
I will take a look, thanks :)

**Comment by Kampi** [comment]
Maybe I updated it because I had this at two different places. TBH I´m not sure why it´s more recent 😄
